language: php

dist: trusty

sudo: false

env:
 - DB=MYSQL CORE_RELEASE=3.2
 - DB=MYSQL CORE_RELEASE=3.3
 - DB=MYSQL CORE_RELEASE=3.4
 - DB=SQLITE3 CORE_RELEASE=3.4

matrix:
  include:
    - php: 7.1
      env: CORE_RELEASE=3.6 DB=MYSQL

before_script:
 - phpenv rehash
 - composer self-update || true
 - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/installer
 - cd ~/builds/ss

script:
 - vendor/bin/phpunit faq/tests/
